server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: managing-travel-tours

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: El-2022-nur

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create

  liquibase:
    change-log: classpath:db.changelog/changelog-master.yml
    enabled: true
    contexts: development
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true